WindowBg = "#121212"                 # 窗口背景颜色（深黑色）
LayoutBg = "#1E1E1E"                 # 布局背景颜色（黑灰色）
ControlBg = "#2C2C2C"                # 控件背景颜色（浅黑灰色）
PrimaryTitle = "#FFFFFF"             # 一级标题颜色（白色）
SecondaryTitle = "#BDBDBD"           # 二级标题颜色（浅灰色）
TertiaryTitle = "#9E9E9E"            # 三级标题颜色（灰色）
BodyText = "#E0E0E0"                 # 正文文本颜色（浅白灰色）
ListItemBg = "#1E1E1E"               # 列表项背景颜色（黑灰色）
ListItemFg = "#E0E0E0"               # 列表项前景颜色（浅白灰色）
ListItemSelectedBg = "#333333"       # 列表项选中背景颜色（深灰色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#2C2C2C"          # 列表项悬停背景颜色（浅黑灰色）
ListItemHoverFg = "#FFFFFF"          # 列表项悬停前景颜色（白色）
ButtonBg = "#333333"                 # 按钮背景颜色（深灰色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#2C2C2C"         # 按钮禁用背景颜色（浅黑灰色）
ButtonDisabledFg = "#757575"         # 按钮禁用前景颜色（深灰色）
TransparentButtonFg = "#E0E0E0"      # 透明按钮前景颜色（浅白灰色）
TransparentButtonBorder = "#757575"  # 透明按钮边框颜色（灰色）
TransparentButtonDisabledFg = "#616161" # 透明按钮禁用前景颜色（暗灰色）
TransparentButtonDisabledBorder = "#2C2C2C" # 透明按钮禁用边框颜色（浅黑灰色）
ButtonHoverMask = "#10FFFFFF"        # 按钮悬停蒙版（10% 白）
ButtonPressedMask = "#20FFFFFF"      # 按钮按下蒙版（20% 白）
AccentColor = "#FF5722"              # 强调背景颜色（亮橙色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#FF7043"              # 强调标题颜色（浅橙色）
AccentHoverBg = "#F4511E"            # 强调悬停背景颜色（深橙色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#BF360C"          # 强调按下背景颜色（暗橙色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#616161"    # 复选框未选中图标颜色（暗灰色）
CheckboxHoverIcon = "#FF5722"        # 复选框悬停图标颜色（亮橙色）
CheckboxCheckedIcon = "#FF7043"      # 复选框选中图标颜色（浅橙色）
CheckboxText = "#E0E0E0"             # 复选框文字颜色（浅白灰色）
CheckboxHoverText = "#FF5722"        # 复选框悬停文字颜色（亮橙色）
CheckboxCheckedText = "#FF7043"      # 复选框选中文字颜色（浅橙色）
ToggleButtonBg = "#1E1E1E"           # 切换按钮背景颜色（黑灰色）
ToggleButtonFg = "#E0E0E0"           # 切换按钮前景颜色（浅白灰色）
ToggleButtonHoverBg = "#2C2C2C"      # 切换按钮悬停背景颜色（浅黑灰色）
ToggleButtonHoverFg = "#FFFFFF"      # 切换按钮悬停前景颜色（白色）
ToggleButtonSelectedBg = "#FF5722"   # 切换按钮选中背景颜色（亮橙色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#424242"              # 开关关闭背景颜色（暗灰色）
SwitchHoverBg = "#FF7043"            # 开关悬停背景颜色（浅橙色）
SwitchOnBg = "#FF5722"               # 开关开启背景颜色（亮橙色）
SwitchOffFg = "#E0E0E0"              # 开关关闭前景颜色（浅白灰色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#80000000"            # 阴影颜色（50% 黑）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
