WindowBg = "#E3F2FD"                 # 窗口背景颜色（淡蓝色）
LayoutBg = "#BBDEFB"                 # 布局背景颜色（浅蓝色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#0D47A1"             # 一级标题颜色（深蓝色）
SecondaryTitle = "#1565C0"           # 二级标题颜色（标准蓝色）
TertiaryTitle = "#1976D2"            # 三级标题颜色（亮蓝色）
BodyText = "#1E88E5"                 # 正文文本颜色（中蓝色）
ListItemBg = "#E3F2FD"               # 列表项背景颜色（淡蓝色）
ListItemFg = "#0D47A1"               # 列表项前景颜色（深蓝色）
ListItemSelectedBg = "#1976D2"       # 列表项选中背景颜色（亮蓝色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#BBDEFB"          # 列表项悬停背景颜色（浅蓝色）
ListItemHoverFg = "#0D47A1"          # 列表项悬停前景颜色（深蓝色）
ButtonBg = "#2986F2"                 # 按钮背景颜色（亮蓝色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#DEE4EE"         # 按钮禁用背景颜色（浅灰蓝色）
ButtonDisabledFg = "#90A4AE"         # 按钮禁用前景颜色（灰蓝色）
TransparentButtonFg = "#1565C0"      # 透明按钮前景颜色（标准蓝色）
TransparentButtonBorder = "#1565C0"  # 透明按钮边框颜色（标准蓝色）
TransparentButtonDisabledFg = "#90A4AE" # 透明按钮禁用前景颜色（灰蓝色）
TransparentButtonDisabledBorder = "#BBDEFB" # 透明按钮禁用边框颜色（浅灰蓝色）
ButtonHoverMask = "#1A0D47A1"        # 按钮悬停蒙版（10% 黑）
ButtonPressedMask = "#440D47A1"      # 按钮按下蒙版（20% 黑）
AccentColor = "#1976D2"              # 强调背景颜色（亮蓝色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#E3F2FD"              # 强调标题颜色（深蓝色）
AccentHoverBg = "#1565C0"            # 强调悬停背景颜色（标准蓝色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#0D47A1"          # 强调按下背景颜色（深蓝色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#90CAF9"    # 复选框未选中图标颜色（浅蓝色）
CheckboxHoverIcon = "#1976D2"        # 复选框悬停图标颜色（亮蓝色）
CheckboxCheckedIcon = "#1565C0"      # 复选框选中图标颜色（标准蓝色）
CheckboxText = "#0D47A1"             # 复选框文字颜色（深蓝色）
CheckboxHoverText = "#1976D2"        # 复选框悬停文字颜色（亮蓝色）
CheckboxCheckedText = "#1565C0"      # 复选框选中文字颜色（标准蓝色）
ToggleButtonBg = "#E3F2FD"           # 切换按钮背景颜色（淡蓝色）
ToggleButtonFg = "#0D47A1"           # 切换按钮前景颜色（深蓝色）
ToggleButtonHoverBg = "#BBDEFB"      # 切换按钮悬停背景颜色（浅蓝色）
ToggleButtonHoverFg = "#0D47A1"      # 切换按钮悬停前景颜色（深蓝色）
ToggleButtonSelectedBg = "#1976D2"   # 切换按钮选中背景颜色（亮蓝色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#BBDEFB"              # 开关关闭背景颜色（浅蓝色）
SwitchHoverBg = "#1976D2"            # 开关悬停背景颜色（亮蓝色）
SwitchOnBg = "#1565C0"               # 开关开启背景颜色（标准蓝色）
SwitchOffFg = "#0D47A1"              # 开关关闭前景颜色（深蓝色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#660D47A1"            # 阴影颜色（25% 黑）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
