WindowBg = "#E0F7FA"                 # 窗口背景颜色（淡青色）
LayoutBg = "#B2EBF2"                 # 布局背景颜色（浅青色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#006064"             # 一级标题颜色（深青色）
SecondaryTitle = "#00838F"           # 二级标题颜色（标准青色）
TertiaryTitle = "#00ACC1"            # 三级标题颜色（亮青色）
BodyText = "#004D40"                 # 正文文本颜色（深绿色，确保对比度）
ListItemBg = "#E0F7FA"               # 列表项背景颜色（淡青色）
ListItemFg = "#004D40"               # 列表项前景颜色（深绿色）
ListItemSelectedBg = "#00838F"       # 列表项选中背景颜色（标准青色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#B2EBF2"          # 列表项悬停背景颜色（浅青色）
ListItemHoverFg = "#004D40"          # 列表项悬停前景颜色（深绿色）
ButtonBg = "#00838F"                 # 按钮背景颜色（标准青色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#B2EBF2"         # 按钮禁用背景颜色（灰青色）
ButtonDisabledFg = "#90A4AE"         # 按钮禁用前景颜色（灰蓝色）
TransparentButtonFg = "#006064"      # 透明按钮前景颜色（深青色）
TransparentButtonBorder = "#006064"  # 透明按钮边框颜色（深青色）
TransparentButtonDisabledFg = "#90A4AE" # 透明按钮禁用前景颜色（灰蓝色）
TransparentButtonDisabledBorder = "#B2EBF2" # 透明按钮禁用边框颜色（灰青色）
ButtonHoverMask = "#1A004D40"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#44004D40"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#00ACC1"              # 强调背景颜色（亮青色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#E0F7FA"              # 强调标题颜色（暖橙色，对比鲜明）
AccentHoverBg = "#00838F"            # 强调悬停背景颜色（标准青色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#006064"          # 强调按下背景颜色（深青色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#80DEEA"    # 复选框未选中图标颜色（浅青色）
CheckboxHoverIcon = "#00ACC1"        # 复选框悬停图标颜色（亮青色）
CheckboxCheckedIcon = "#00838F"      # 复选框选中图标颜色（标准青色）
CheckboxText = "#004D40"             # 复选框文字颜色（深绿色）
CheckboxHoverText = "#00838F"        # 复选框悬停文字颜色（标准青色）
CheckboxCheckedText = "#00ACC1"      # 复选框选中文字颜色（亮青色）
ToggleButtonBg = "#E0F7FA"           # 切换按钮背景颜色（淡青色）
ToggleButtonFg = "#004D40"           # 切换按钮前景颜色（深绿色）
ToggleButtonHoverBg = "#B2EBF2"      # 切换按钮悬停背景颜色（浅青色）
ToggleButtonHoverFg = "#004D40"      # 切换按钮悬停前景颜色（深绿色）
ToggleButtonSelectedBg = "#00838F"   # 切换按钮选中背景颜色（标准青色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#B2EBF2"              # 开关关闭背景颜色（灰青色）
SwitchHoverBg = "#00ACC1"            # 开关悬停背景颜色（亮青色）
SwitchOnBg = "#006064"               # 开关开启背景颜色（深青色）
SwitchOffFg = "#004D40"              # 开关关闭前景颜色（深绿色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#66004D40"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
