WindowBg = "#F1F8E9"                 # 窗口背景颜色（淡青草绿）
LayoutBg = "#DCEDC8"                 # 布局背景颜色（浅青草绿）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#2E7D32"             # 一级标题颜色（深青草绿）
SecondaryTitle = "#388E3C"           # 二级标题颜色（标准青草绿）
TertiaryTitle = "#43A047"            # 三级标题颜色（亮青草绿）
BodyText = "#1B5E20"                 # 正文文本颜色（深绿色，确保对比）
ListItemBg = "#F1F8E9"               # 列表项背景颜色（淡青草绿）
ListItemFg = "#2E7D32"               # 列表项前景颜色（深青草绿）
ListItemSelectedBg = "#388E3C"       # 列表项选中背景颜色（标准青草绿）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#DCEDC8"          # 列表项悬停背景颜色（浅青草绿）
ListItemHoverFg = "#2E7D32"          # 列表项悬停前景颜色（深青草绿）
ButtonBg = "#388E3C"                 # 按钮背景颜色（标准青草绿）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#DCEDC8"         # 按钮禁用背景颜色（浅青草绿）
ButtonDisabledFg = "#9E9E9E"         # 按钮禁用前景颜色（灰色）
TransparentButtonFg = "#2E7D32"      # 透明按钮前景颜色（深青草绿）
TransparentButtonBorder = "#2E7D32"  # 透明按钮边框颜色（深青草绿）
TransparentButtonDisabledFg = "#9E9E9E" # 透明按钮禁用前景颜色（灰色）
TransparentButtonDisabledBorder = "#DCEDC8" # 透明按钮禁用边框颜色（浅青草绿）
ButtonHoverMask = "#1A1B5E20"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#441B5E20"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#43A047"              # 强调背景颜色（亮青草绿）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#F1F8E9"              # 强调标题颜色（暖橙色，对比鲜明）
AccentHoverBg = "#2E7D32"            # 强调悬停背景颜色（深青草绿）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#1B5E20"          # 强调按下背景颜色（暗绿色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#A5D6A7"    # 复选框未选中图标颜色（灰绿色）
CheckboxHoverIcon = "#388E3C"        # 复选框悬停图标颜色（标准青草绿）
CheckboxCheckedIcon = "#2E7D32"      # 复选框选中图标颜色（深青草绿）
CheckboxText = "#2E7D32"             # 复选框文字颜色（深青草绿）
CheckboxHoverText = "#43A047"        # 复选框悬停文字颜色（亮青草绿）
CheckboxCheckedText = "#388E3C"      # 复选框选中文字颜色（标准青草绿）
ToggleButtonBg = "#F1F8E9"           # 切换按钮背景颜色（淡青草绿）
ToggleButtonFg = "#2E7D32"           # 切换按钮前景颜色（深青草绿）
ToggleButtonHoverBg = "#DCEDC8"      # 切换按钮悬停背景颜色（浅青草绿）
ToggleButtonHoverFg = "#2E7D32"      # 切换按钮悬停前景颜色（深青草绿）
ToggleButtonSelectedBg = "#388E3C"   # 切换按钮选中背景颜色（标准青草绿）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#A5D6A7"              # 开关关闭背景颜色（灰绿色）
SwitchHoverBg = "#43A047"            # 开关悬停背景颜色（亮青草绿）
SwitchOnBg = "#2E7D32"               # 开关开启背景颜色（深青草绿）
SwitchOffFg = "#2E7D32"              # 开关关闭前景颜色（深青草绿）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#661B5E20"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（标准绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
