WindowBg = "#FAE3E3"                 # 窗口背景颜色（淡印度红）
LayoutBg = "#F4CACA"                 # 布局背景颜色（浅印度红）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#B22222"             # 一级标题颜色（深印度红）
SecondaryTitle = "#C04040"           # 二级标题颜色（标准印度红）
TertiaryTitle = "#D9534F"            # 三级标题颜色（亮印度红）
BodyText = "#6D0000"                 # 正文文本颜色（暗红色，确保对比度）
ListItemBg = "#FAE3E3"               # 列表项背景颜色（淡印度红）
ListItemFg = "#6D0000"               # 列表项前景颜色（暗红色）
ListItemSelectedBg = "#C04040"       # 列表项选中背景颜色（标准印度红）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#F4CACA"          # 列表项悬停背景颜色（浅印度红）
ListItemHoverFg = "#6D0000"          # 列表项悬停前景颜色（暗红色）
ButtonBg = "#C04040"                 # 按钮背景颜色（标准印度红）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#FFF9EE"         # 按钮禁用背景颜色（灰红色）
ButtonDisabledFg = "#A1887F"         # 按钮禁用前景颜色（灰棕色）
TransparentButtonFg = "#B22222"      # 透明按钮前景颜色（深印度红）
TransparentButtonBorder = "#C04040"  # 透明按钮边框颜色（标准印度红）
TransparentButtonDisabledFg = "#A1887F" # 透明按钮禁用前景颜色（灰棕色）
TransparentButtonDisabledBorder = "#E4B6B6" # 透明按钮禁用边框颜色（灰红色）
ButtonHoverMask = "#1A6D0000"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#446D0000"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#D9534F"              # 强调背景颜色（亮印度红）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#FFC107"              # 强调标题颜色（金黄色，提供强烈对比）
AccentHoverBg = "#C04040"            # 强调悬停背景颜色（标准印度红）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#B22222"          # 强调按下背景颜色（深印度红）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#E57373"    # 复选框未选中图标颜色（浅红色）
CheckboxHoverIcon = "#C04040"        # 复选框悬停图标颜色（标准印度红）
CheckboxCheckedIcon = "#B22222"      # 复选框选中图标颜色（深印度红）
CheckboxText = "#6D0000"             # 复选框文字颜色（暗红色）
CheckboxHoverText = "#C04040"        # 复选框悬停文字颜色（标准印度红）
CheckboxCheckedText = "#B22222"      # 复选框选中文字颜色（深印度红）
ToggleButtonBg = "#FAE3E3"           # 切换按钮背景颜色（淡印度红）
ToggleButtonFg = "#6D0000"           # 切换按钮前景颜色（暗红色）
ToggleButtonHoverBg = "#F4CACA"      # 切换按钮悬停背景颜色（浅印度红）
ToggleButtonHoverFg = "#6D0000"      # 切换按钮悬停前景颜色（暗红色）
ToggleButtonSelectedBg = "#C04040"   # 切换按钮选中背景颜色（标准印度红）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#E4B6B6"              # 开关关闭背景颜色（灰红色）
SwitchHoverBg = "#C04040"            # 开关悬停背景颜色（标准印度红）
SwitchOnBg = "#B22222"               # 开关开启背景颜色（深印度红）
SwitchOffFg = "#6D0000"              # 开关关闭前景颜色（暗红色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#666D0000"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
