WindowBg = "#F0EDE4"                 # 窗口背景颜色（淡卡其色）
LayoutBg = "#E0D8C3"                 # 布局背景颜色（浅卡其色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#6D4C41"             # 一级标题颜色（深棕卡其）
SecondaryTitle = "#8D6E63"           # 二级标题颜色（标准卡其棕）
TertiaryTitle = "#A1887F"            # 三级标题颜色（亮卡其灰）
BodyText = "#4E342E"                 # 正文文本颜色（深棕色，确保对比）
ListItemBg = "#F0EDE4"               # 列表项背景颜色（淡卡其色）
ListItemFg = "#6D4C41"               # 列表项前景颜色（深棕卡其色）
ListItemSelectedBg = "#8D6E63"       # 列表项选中背景颜色（标准卡其棕）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#E0D8C3"          # 列表项悬停背景颜色（浅卡其色）
ListItemHoverFg = "#6D4C41"          # 列表项悬停前景颜色（深棕卡其色）
ButtonBg = "#8D6E63"                 # 按钮背景颜色（标准卡其棕）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#D7CCC8"         # 按钮禁用背景颜色（浅灰卡其）
ButtonDisabledFg = "#BCAAA4"         # 按钮禁用前景颜色（灰棕色）
TransparentButtonFg = "#6D4C41"      # 透明按钮前景颜色（深棕卡其色）
TransparentButtonBorder = "#6D4C41"  # 透明按钮边框颜色（深棕卡其色）
TransparentButtonDisabledFg = "#BCAAA4" # 透明按钮禁用前景颜色（灰棕色）
TransparentButtonDisabledBorder = "#D7CCC8" # 透明按钮禁用边框颜色（浅灰卡其）
ButtonHoverMask = "#1A000000"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#33000000"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#A1887F"              # 强调背景颜色（亮卡其灰）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#F0EDE4"              # 强调标题颜色（深棕色，对比鲜明）
AccentHoverBg = "#8D6E63"            # 强调悬停背景颜色（标准卡其棕）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#6D4C41"          # 强调按下背景颜色（深棕卡其色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#BCAAA4"    # 复选框未选中图标颜色（灰卡其色）
CheckboxHoverIcon = "#8D6E63"        # 复选框悬停图标颜色（标准卡其棕）
CheckboxCheckedIcon = "#6D4C41"      # 复选框选中图标颜色（深棕卡其色）
CheckboxText = "#4E342E"             # 复选框文字颜色（深棕色）
CheckboxHoverText = "#8D6E63"        # 复选框悬停文字颜色（标准卡其棕）
CheckboxCheckedText = "#6D4C41"      # 复选框选中文字颜色（深棕卡其色）
ToggleButtonBg = "#F0EDE4"           # 切换按钮背景颜色（淡卡其色）
ToggleButtonFg = "#6D4C41"           # 切换按钮前景颜色（深棕卡其色）
ToggleButtonHoverBg = "#E0D8C3"      # 切换按钮悬停背景颜色（浅卡其色）
ToggleButtonHoverFg = "#4E342E"      # 切换按钮悬停前景颜色（深棕色）
ToggleButtonSelectedBg = "#8D6E63"   # 切换按钮选中背景颜色（标准卡其棕）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#D7CCC8"              # 开关关闭背景颜色（灰卡其色）
SwitchHoverBg = "#8D6E63"            # 开关悬停背景颜色（标准卡其棕）
SwitchOnBg = "#6D4C41"               # 开关开启背景颜色（深棕卡其色）
SwitchOffFg = "#4E342E"              # 开关关闭前景颜色（深棕色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#66000000"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
