WindowBg = "#FFF8E1"                 # 窗口背景颜色（淡橙色）
LayoutBg = "#FFECB3"                 # 布局背景颜色（浅橙色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#E64A19"             # 一级标题颜色（深橙色）
SecondaryTitle = "#FB8C00"           # 二级标题颜色（标准橙色）
TertiaryTitle = "#FF9800"            # 三级标题颜色（亮橙色）
BodyText = "#4E342E"                 # 正文文本颜色（深棕色，确保对比）
ListItemBg = "#FFF8E1"               # 列表项背景颜色（淡橙色）
ListItemFg = "#E64A19"               # 列表项前景颜色（深橙色）
ListItemSelectedBg = "#FB8C00"       # 列表项选中背景颜色（标准橙色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#FFECB3"          # 列表项悬停背景颜色（浅橙色）
ListItemHoverFg = "#E64A19"          # 列表项悬停前景颜色（深橙色）
ButtonBg = "#FB8C00"                 # 按钮背景颜色（标准橙色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#FFCC80"         # 按钮禁用背景颜色（浅灰橙）
ButtonDisabledFg = "#A1887F"         # 按钮禁用前景颜色（灰棕色）
TransparentButtonFg = "#E64A19"      # 透明按钮前景颜色（深橙色）
TransparentButtonBorder = "#E64A19"  # 透明按钮边框颜色（深橙色）
TransparentButtonDisabledFg = "#A1887F" # 透明按钮禁用前景颜色（灰棕色）
TransparentButtonDisabledBorder = "#FFCC80" # 透明按钮禁用边框颜色（浅灰橙）
ButtonHoverMask = "#1A4E342E"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#444E342E"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#FF9800"              # 强调背景颜色（亮橙色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#FFF8E1"              # 强调标题颜色（暖橙红，对比鲜明）
AccentHoverBg = "#F57C00"            # 强调悬停背景颜色（深橙色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#E64A19"          # 强调按下背景颜色（更深橙色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#FFCC80"    # 复选框未选中图标颜色（浅灰橙）
CheckboxHoverIcon = "#FB8C00"        # 复选框悬停图标颜色（标准橙色）
CheckboxCheckedIcon = "#F57C00"      # 复选框选中图标颜色（深橙色）
CheckboxText = "#E64A19"             # 复选框文字颜色（深橙色）
CheckboxHoverText = "#FB8C00"        # 复选框悬停文字颜色（标准橙色）
CheckboxCheckedText = "#F57C00"      # 复选框选中文字颜色（深橙色）
ToggleButtonBg = "#FFF8E1"           # 切换按钮背景颜色（淡橙色）
ToggleButtonFg = "#E64A19"           # 切换按钮前景颜色（深橙色）
ToggleButtonHoverBg = "#FFECB3"      # 切换按钮悬停背景颜色（浅橙色）
ToggleButtonHoverFg = "#E64A19"      # 切换按钮悬停前景颜色（深橙色）
ToggleButtonSelectedBg = "#FB8C00"   # 切换按钮选中背景颜色（标准橙色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#FFCC80"              # 开关关闭背景颜色（浅灰橙）
SwitchHoverBg = "#FB8C00"            # 开关悬停背景颜色（标准橙色）
SwitchOnBg = "#E64A19"               # 开关开启背景颜色（深橙色）
SwitchOffFg = "#6D4C41"              # 开关关闭前景颜色（深棕色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#664E342E"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
