WindowBg = "#FCE4EC"                 # 窗口背景颜色（淡粉色）
LayoutBg = "#F8BBD0"                 # 布局背景颜色（浅粉色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#D81B60"             # 一级标题颜色（深粉色）
SecondaryTitle = "#E91E63"           # 二级标题颜色（标准粉色）
TertiaryTitle = "#F06292"            # 三级标题颜色（亮粉色）
BodyText = "#AD1457"                 # 正文文本颜色（暗粉色）
ListItemBg = "#FCE4EC"               # 列表项背景颜色（淡粉色）
ListItemFg = "#880E4F"               # 列表项前景颜色（深紫粉色）
ListItemSelectedBg = "#E91E63"       # 列表项选中背景颜色（标准粉色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#F8BBD0"          # 列表项悬停背景颜色（浅粉色）
ListItemHoverFg = "#880E4F"          # 列表项悬停前景颜色（深紫粉色）
ButtonBg = "#F92E73"                 # 按钮背景颜色（标准粉色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#F8BBD0"         # 按钮禁用背景颜色（浅灰粉色）
ButtonDisabledFg = "#D1C4E9"         # 按钮禁用前景颜色（灰紫色）
TransparentButtonFg = "#D81B60"      # 透明按钮前景颜色（深粉色）
TransparentButtonBorder = "#D81B60"  # 透明按钮边框颜色（深粉色）
TransparentButtonDisabledFg = "#D1C4E9" # 透明按钮禁用前景颜色（灰紫色）
TransparentButtonDisabledBorder = "#F8BBD0" # 透明按钮禁用边框颜色（浅灰粉色）
ButtonHoverMask = "#1AAD1457"        # 按钮悬停蒙版（10% 黑）
ButtonPressedMask = "#44AD1457"      # 按钮按下蒙版（20% 黑）
AccentColor = "#E91E63"              # 强调背景颜色（标准粉色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#FCE4EC"              # 强调标题颜色（暗粉色）
AccentHoverBg = "#D81B60"            # 强调悬停背景颜色（深粉色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#880E4F"          # 强调按下背景颜色（深紫粉色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#F8BBD0"    # 复选框未选中图标颜色（浅灰粉色）
CheckboxHoverIcon = "#E91E63"        # 复选框悬停图标颜色（标准粉色）
CheckboxCheckedIcon = "#D81B60"      # 复选框选中图标颜色（深粉色）
CheckboxText = "#880E4F"             # 复选框文字颜色（深紫粉色）
CheckboxHoverText = "#E91E63"        # 复选框悬停文字颜色（标准粉色）
CheckboxCheckedText = "#D81B60"      # 复选框选中文字颜色（深粉色）
ToggleButtonBg = "#FCE4EC"           # 切换按钮背景颜色（淡粉色）
ToggleButtonFg = "#880E4F"           # 切换按钮前景颜色（深紫粉色）
ToggleButtonHoverBg = "#F8BBD0"      # 切换按钮悬停背景颜色（浅粉色）
ToggleButtonHoverFg = "#880E4F"      # 切换按钮悬停前景颜色（深紫粉色）
ToggleButtonSelectedBg = "#E91E63"   # 切换按钮选中背景颜色（标准粉色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#F8BBD0"              # 开关关闭背景颜色（浅粉色）
SwitchHoverBg = "#D81B60"            # 开关悬停背景颜色（深粉色）
SwitchOnBg = "#AD1457"               # 开关开启背景颜色（暗粉色）
SwitchOffFg = "#880E4F"              # 开关关闭前景颜色（深紫粉色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#66AD1457"            # 阴影颜色（25% 黑）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
