WindowBg = "#F3E5F5"                 # 窗口背景颜色（淡紫色）
LayoutBg = "#E1BEE7"                 # 布局背景颜色（浅紫色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#6A1B9A"             # 一级标题颜色（深卡罗兰紫）
SecondaryTitle = "#7B1FA2"           # 二级标题颜色（标准卡罗兰紫）
TertiaryTitle = "#8E24AA"            # 三级标题颜色（亮卡罗兰紫）
BodyText = "#4A148C"                 # 正文文本颜色（深紫色，确保对比度）
ListItemBg = "#F3E5F5"               # 列表项背景颜色（淡紫色）
ListItemFg = "#6A1B9A"               # 列表项前景颜色（深卡罗兰紫）
ListItemSelectedBg = "#7B1FA2"       # 列表项选中背景颜色（标准卡罗兰紫）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#E1BEE7"          # 列表项悬停背景颜色（浅紫色）
ListItemHoverFg = "#6A1B9A"          # 列表项悬停前景颜色（深卡罗兰紫）
ButtonBg = "#7B1FA2"                 # 按钮背景颜色（标准卡罗兰紫）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#D1C4E9"         # 按钮禁用背景颜色（灰紫色）
ButtonDisabledFg = "#B39DDB"         # 按钮禁用前景颜色（浅灰紫）
TransparentButtonFg = "#6A1B9A"      # 透明按钮前景颜色（深卡罗兰紫）
TransparentButtonBorder = "#7B1FA2"  # 透明按钮边框颜色（标准卡罗兰紫）
TransparentButtonDisabledFg = "#B39DDB" # 透明按钮禁用前景颜色（浅灰紫）
TransparentButtonDisabledBorder = "#D1C4E9" # 透明按钮禁用边框颜色（灰紫色）
ButtonHoverMask = "#1A000000"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#33000000"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#8E24AA"              # 强调背景颜色（亮卡罗兰紫）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#FFB300"              # 强调标题颜色（亮金黄色，对比强烈）
AccentHoverBg = "#7B1FA2"            # 强调悬停背景颜色（标准卡罗兰紫）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#6A1B9A"          # 强调按下背景颜色（深卡罗兰紫）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#CE93D8"    # 复选框未选中图标颜色（浅灰紫色）
CheckboxHoverIcon = "#8E24AA"        # 复选框悬停图标颜色（亮卡罗兰紫）
CheckboxCheckedIcon = "#7B1FA2"      # 复选框选中图标颜色（标准卡罗兰紫）
CheckboxText = "#6A1B9A"             # 复选框文字颜色（深卡罗兰紫）
CheckboxHoverText = "#8E24AA"        # 复选框悬停文字颜色（亮卡罗兰紫）
CheckboxCheckedText = "#7B1FA2"      # 复选框选中文字颜色（标准卡罗兰紫）
ToggleButtonBg = "#F3E5F5"           # 切换按钮背景颜色（淡紫色）
ToggleButtonFg = "#6A1B9A"           # 切换按钮前景颜色（深卡罗兰紫）
ToggleButtonHoverBg = "#E1BEE7"      # 切换按钮悬停背景颜色（浅紫色）
ToggleButtonHoverFg = "#6A1B9A"      # 切换按钮悬停前景颜色（深卡罗兰紫）
ToggleButtonSelectedBg = "#7B1FA2"   # 切换按钮选中背景颜色（标准卡罗兰紫）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#D1C4E9"              # 开关关闭背景颜色（灰紫色）
SwitchHoverBg = "#8E24AA"            # 开关悬停背景颜色（亮卡罗兰紫）
SwitchOnBg = "#6A1B9A"               # 开关开启背景颜色（深卡罗兰紫）
SwitchOffFg = "#6A1B9A"              # 开关关闭前景颜色（深卡罗兰紫）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#66000000"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
