WindowBg = "#FFF5F5F5"               # 窗口背景颜色（淡灰白色）
LayoutBg = "#FFFAE0E0"               # 布局背景颜色（浅红色）
ControlBg = "#FFFFFFFF"              # 控件背景颜色（白色）
PrimaryTitle = "#B71C1C"             # 一级标题颜色（深大红色）
SecondaryTitle = "#C62828"           # 二级标题颜色（标准大红色）
TertiaryTitle = "#D32F2F"            # 三级标题颜色（亮大红色）
BodyText = "#6D0000"                 # 正文文本颜色（暗红色，确保对比度）
ListItemBg = "#FFFAE0E0"             # 列表项背景颜色（浅红色）
ListItemFg = "#B71C1C"               # 列表项前景颜色（深大红色）
ListItemSelectedBg = "#C62828"       # 列表项选中背景颜色（标准大红色）
ListItemSelectedFg = "#FFFFFFFF"     # 列表项选中前景颜色（白色）
ListItemHoverBg = "#FFD7C7C7"        # 列表项悬停背景颜色（灰红色）
ListItemHoverFg = "#B71C1C"          # 列表项悬停前景颜色（深大红色）
ButtonBg = "#C62828"                 # 按钮背景颜色（标准大红色）
ButtonFg = "#FFFFFFFF"               # 按钮前景颜色（白色）
ButtonDisabledBg = "#FFBCAAA4"       # 按钮禁用背景颜色（灰红色）
ButtonDisabledFg = "#FF9E9E9E"       # 按钮禁用前景颜色（灰色）
TransparentButtonFg = "#B71C1C"      # 透明按钮前景颜色（深大红色）
TransparentButtonBorder = "#C62828"  # 透明按钮边框颜色（标准大红色）
TransparentButtonDisabledFg = "#FF9E9E9E" # 透明按钮禁用前景颜色（灰色）
TransparentButtonDisabledBorder = "#FFD7C7C7" # 透明按钮禁用边框颜色（浅灰红色）
ButtonHoverMask = "#1A000000"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#33000000"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#D32F2F"              # 强调背景颜色（亮大红色）
AccentFg = "#FFFFFFFF"               # 强调前景颜色（白色）
AccentTitle = "#FFC107"              # 强调标题颜色（明亮金黄色，对比强烈）
AccentHoverBg = "#C62828"            # 强调悬停背景颜色（标准大红色）
AccentHoverFg = "#FFFFFFFF"          # 强调悬停前景颜色（白色）
AccentPressedBg = "#B71C1C"          # 强调按下背景颜色（深大红色）
AccentPressedFg = "#FFFFFFFF"        # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#EF9A9A"    # 复选框未选中图标颜色（浅红色）
CheckboxHoverIcon = "#C62828"        # 复选框悬停图标颜色（标准大红色）
CheckboxCheckedIcon = "#B71C1C"      # 复选框选中图标颜色（深大红色）
CheckboxText = "#6D0000"             # 复选框文字颜色（暗红色）
CheckboxHoverText = "#C62828"        # 复选框悬停文字颜色（标准大红色）
CheckboxCheckedText = "#B71C1C"      # 复选框选中文字颜色（深大红色）
ToggleButtonBg = "#FFFAE0E0"         # 切换按钮背景颜色（浅红色）
ToggleButtonFg = "#6D0000"           # 切换按钮前景颜色（暗红色）
ToggleButtonHoverBg = "#FFD7C7C7"    # 切换按钮悬停背景颜色（灰红色）
ToggleButtonHoverFg = "#B71C1C"      # 切换按钮悬停前景颜色（深大红色）
ToggleButtonSelectedBg = "#C62828"   # 切换按钮选中背景颜色（标准大红色）
ToggleButtonSelectedFg = "#FFFFFFFF" # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#FFD7C7C7"            # 开关关闭背景颜色（灰红色）
SwitchHoverBg = "#C62828"            # 开关悬停背景颜色（标准大红色）
SwitchOnBg = "#B71C1C"               # 开关开启背景颜色（深大红色）
SwitchOffFg = "#6D0000"              # 开关关闭前景颜色（暗红色）
SwitchHoverFg = "#FFFFFFFF"          # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFFFF"             # 开关开启前景颜色（白色）
ShadowColor = "#66000000"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
