WindowBg = "#E1F5FE"                 # 窗口背景颜色（淡天蓝色）
LayoutBg = "#B3E5FC"                 # 布局背景颜色（浅天蓝色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#0277BD"             # 一级标题颜色（深天蓝色）
SecondaryTitle = "#0288D1"           # 二级标题颜色（标准天蓝色）
TertiaryTitle = "#039BE5"            # 三级标题颜色（亮天蓝色）
BodyText = "#01579B"                 # 正文文本颜色（深蓝色，确保对比度）
ListItemBg = "#E1F5FE"               # 列表项背景颜色（淡天蓝色）
ListItemFg = "#01579B"               # 列表项前景颜色（深蓝色）
ListItemSelectedBg = "#0288D1"       # 列表项选中背景颜色（标准天蓝色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#B3E5FC"          # 列表项悬停背景颜色（浅天蓝色）
ListItemHoverFg = "#01579B"          # 列表项悬停前景颜色（深蓝色）
ButtonBg = "#0288D1"                 # 按钮背景颜色（标准天蓝色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#B3E5FC"         # 按钮禁用背景颜色（灰天蓝色）
ButtonDisabledFg = "#90A4AE"         # 按钮禁用前景颜色（灰蓝色）
TransparentButtonFg = "#0277BD"      # 透明按钮前景颜色（深天蓝色）
TransparentButtonBorder = "#0277BD"  # 透明按钮边框颜色（深天蓝色）
TransparentButtonDisabledFg = "#90A4AE" # 透明按钮禁用前景颜色（灰蓝色）
TransparentButtonDisabledBorder = "#B3E5FC" # 透明按钮禁用边框颜色（灰天蓝色）
ButtonHoverMask = "#1A01579B"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#4401579B"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#039BE5"              # 强调背景颜色（亮天蓝色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#E1F5FE"              # 强调标题颜色（亮橙色，对比强烈）
AccentHoverBg = "#0277BD"            # 强调悬停背景颜色（深天蓝色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#01579B"          # 强调按下背景颜色（深蓝色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#81D4FA"    # 复选框未选中图标颜色（浅天蓝）
CheckboxHoverIcon = "#0288D1"        # 复选框悬停图标颜色（标准天蓝色）
CheckboxCheckedIcon = "#0277BD"      # 复选框选中图标颜色（深天蓝色）
CheckboxText = "#01579B"             # 复选框文字颜色（深蓝色）
CheckboxHoverText = "#0288D1"        # 复选框悬停文字颜色（标准天蓝色）
CheckboxCheckedText = "#0277BD"      # 复选框选中文字颜色（深天蓝色）
ToggleButtonBg = "#E1F5FE"           # 切换按钮背景颜色（淡天蓝色）
ToggleButtonFg = "#01579B"           # 切换按钮前景颜色（深蓝色）
ToggleButtonHoverBg = "#B3E5FC"      # 切换按钮悬停背景颜色（浅天蓝色）
ToggleButtonHoverFg = "#01579B"      # 切换按钮悬停前景颜色（深蓝色）
ToggleButtonSelectedBg = "#0288D1"   # 切换按钮选中背景颜色（标准天蓝色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#B3E5FC"              # 开关关闭背景颜色（浅天蓝色）
SwitchHoverBg = "#039BE5"            # 开关悬停背景颜色（亮天蓝色）
SwitchOnBg = "#0277BD"               # 开关开启背景颜色（深天蓝色）
SwitchOffFg = "#01579B"              # 开关关闭前景颜色（深蓝色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#6601579B"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
