WindowBg = "#E0F2F1"                 # 窗口背景颜色（淡蓝绿色）
LayoutBg = "#B2DFDB"                 # 布局背景颜色（浅蓝绿色）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#004D40"             # 一级标题颜色（深蓝绿色）
SecondaryTitle = "#00796B"           # 二级标题颜色（标准蓝绿色）
TertiaryTitle = "#009688"            # 三级标题颜色（亮蓝绿色）
BodyText = "#004D40"                 # 正文文本颜色（暗蓝绿色）
ListItemBg = "#E0F2F1"               # 列表项背景颜色（淡蓝绿色）
ListItemFg = "#004D40"               # 列表项前景颜色（深蓝绿色）
ListItemSelectedBg = "#00796B"       # 列表项选中背景颜色（标准蓝绿色）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#B2DFDB"          # 列表项悬停背景颜色（浅蓝绿色）
ListItemHoverFg = "#004D40"          # 列表项悬停前景颜色（深蓝绿色）
ButtonBg = "#00796B"                 # 按钮背景颜色（标准蓝绿色）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#ECFFFE"         # 按钮禁用背景颜色（浅蓝绿色）
ButtonDisabledFg = "#80CBC4"         # 按钮禁用前景颜色（灰蓝绿色）
TransparentButtonFg = "#00796B"      # 透明按钮前景颜色（标准蓝绿色）
TransparentButtonBorder = "#00796B"  # 透明按钮边框颜色（标准蓝绿色）
TransparentButtonDisabledFg = "#80CBC4" # 透明按钮禁用前景颜色（灰蓝绿色）
TransparentButtonDisabledBorder = "#B2DFDB" # 透明按钮禁用边框颜色（浅蓝绿色）
ButtonHoverMask = "#1A004D40"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#44004D40"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#009688"              # 强调背景颜色（亮蓝绿色）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#E0F2F1"              # 强调标题颜色（暖橙色，对比效果强）
AccentHoverBg = "#00897B"            # 强调悬停背景颜色（稍深蓝绿色）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#00695C"          # 强调按下背景颜色（深蓝绿色）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#80CBC4"    # 复选框未选中图标颜色（灰蓝绿色）
CheckboxHoverIcon = "#009688"        # 复选框悬停图标颜色（亮蓝绿色）
CheckboxCheckedIcon = "#00796B"      # 复选框选中图标颜色（标准蓝绿色）
CheckboxText = "#004D40"             # 复选框文字颜色（深蓝绿色）
CheckboxHoverText = "#00796B"        # 复选框悬停文字颜色（标准蓝绿色）
CheckboxCheckedText = "#009688"      # 复选框选中文字颜色（亮蓝绿色）
ToggleButtonBg = "#E0F2F1"           # 切换按钮背景颜色（淡蓝绿色）
ToggleButtonFg = "#004D40"           # 切换按钮前景颜色（深蓝绿色）
ToggleButtonHoverBg = "#B2DFDB"      # 切换按钮悬停背景颜色（浅蓝绿色）
ToggleButtonHoverFg = "#004D40"      # 切换按钮悬停前景颜色（深蓝绿色）
ToggleButtonSelectedBg = "#00796B"   # 切换按钮选中背景颜色（标准蓝绿色）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#B2DFDB"              # 开关关闭背景颜色（浅蓝绿色）
SwitchHoverBg = "#00897B"            # 开关悬停背景颜色（稍深蓝绿色）
SwitchOnBg = "#004D40"               # 开关开启背景颜色（深蓝绿色）
SwitchOffFg = "#004D40"              # 开关关闭前景颜色（深蓝绿色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#66004D40"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）

