WindowBg = "#FFFDE7"                 # 窗口背景颜色（淡明黄）
LayoutBg = "#FFF9C4"                 # 布局背景颜色（浅明黄）
ControlBg = "#FFFFFF"                # 控件背景颜色（白色）
PrimaryTitle = "#F57F17"             # 一级标题颜色（深明黄橙）
SecondaryTitle = "#FBC02D"           # 二级标题颜色（标准明黄）
TertiaryTitle = "#FFCA28"            # 三级标题颜色（亮明黄）
BodyText = "#795548"                 # 正文文本颜色（深棕色）
ListItemBg = "#FFFDE7"               # 列表项背景颜色（淡明黄）
ListItemFg = "#5D4037"               # 列表项前景颜色（深棕色）
ListItemSelectedBg = "#FBC02D"       # 列表项选中背景颜色（标准明黄）
ListItemSelectedFg = "#FFFFFF"       # 列表项选中前景颜色（白色）
ListItemHoverBg = "#FFF9C4"          # 列表项悬停背景颜色（浅明黄）
ListItemHoverFg = "#5D4037"          # 列表项悬停前景颜色（深棕色）
ButtonBg = "#FBC02D"                 # 按钮背景颜色（标准明黄）
ButtonFg = "#FFFFFF"                 # 按钮前景颜色（白色）
ButtonDisabledBg = "#FFF7EE"         # 按钮禁用背景颜色（灰黄色）
ButtonDisabledFg = "#A1887F"         # 按钮禁用前景颜色（灰棕色）
TransparentButtonFg = "#F57F17"      # 透明按钮前景颜色（深明黄橙）
TransparentButtonBorder = "#F57F17"  # 透明按钮边框颜色（深明黄橙）
TransparentButtonDisabledFg = "#A1887F" # 透明按钮禁用前景颜色（灰棕色）
TransparentButtonDisabledBorder = "#FFE082" # 透明按钮禁用边框颜色（灰黄色）
ButtonHoverMask = "#1A795548"        # 按钮悬停蒙版（10% 黑，ARGB 格式）
ButtonPressedMask = "#44795548"      # 按钮按下蒙版（20% 黑，ARGB 格式）
AccentColor = "#FFCA28"              # 强调背景颜色（亮明黄）
AccentFg = "#FFFFFF"                 # 强调前景颜色（白色）
AccentTitle = "#FFFDE7"              # 强调标题颜色（暖橙红，形成强烈对比）
AccentHoverBg = "#FBC02D"            # 强调悬停背景颜色（标准明黄）
AccentHoverFg = "#FFFFFF"            # 强调悬停前景颜色（白色）
AccentPressedBg = "#F57F17"          # 强调按下背景颜色（深明黄橙）
AccentPressedFg = "#FFFFFF"          # 强调按下前景颜色（白色）
CheckboxUncheckedIcon = "#FFE082"    # 复选框未选中图标颜色（灰黄色）
CheckboxHoverIcon = "#FBC02D"        # 复选框悬停图标颜色（标准明黄）
CheckboxCheckedIcon = "#F57F17"      # 复选框选中图标颜色（深明黄橙）
CheckboxText = "#5D4037"             # 复选框文字颜色（深棕色）
CheckboxHoverText = "#FBC02D"        # 复选框悬停文字颜色（标准明黄）
CheckboxCheckedText = "#F57F17"      # 复选框选中文字颜色（深明黄橙）
ToggleButtonBg = "#FFFDE7"           # 切换按钮背景颜色（淡明黄）
ToggleButtonFg = "#5D4037"           # 切换按钮前景颜色（深棕色）
ToggleButtonHoverBg = "#FFF9C4"      # 切换按钮悬停背景颜色（浅明黄）
ToggleButtonHoverFg = "#5D4037"      # 切换按钮悬停前景颜色（深棕色）
ToggleButtonSelectedBg = "#FBC02D"   # 切换按钮选中背景颜色（标准明黄）
ToggleButtonSelectedFg = "#FFFFFF"   # 切换按钮选中前景颜色（白色）
SwitchOffBg = "#FFE082"              # 开关关闭背景颜色（灰黄色）
SwitchHoverBg = "#FBC02D"            # 开关悬停背景颜色（标准明黄）
SwitchOnBg = "#F57F17"               # 开关开启背景颜色（深明黄橙）
SwitchOffFg = "#5D4037"              # 开关关闭前景颜色（深棕色）
SwitchHoverFg = "#FFFFFF"            # 开关悬停前景颜色（白色）
SwitchOnFg = "#FFFFFF"               # 开关开启前景颜色（白色）
ShadowColor = "#66795548"            # 阴影颜色（40% 黑，ARGB 格式）
SuccessColor = "#4CAF50"             # 成功颜色（绿色）
InfoColor = "#29B6F6"                # 信息颜色（亮蓝色）
WarningColor = "#FFB300"             # 警告颜色（亮黄色）
ErrorColor = "#D32F2F"               # 错误颜色（深红色）
