# Dark Theme Configuration

# 背景颜色：深色背景
BackgroundColor = "#121212"

# 前景颜色：浅灰色，用于文本
ForegroundColor = "#E0E0E0"

# 强调背景颜色：深灰色，用于按钮等主要交互元素
AccentBackgroundColor = "#646464"

# 强调前景颜色：接近白色，用于强调按钮上的文本
AccentForegroundColor = "#FAFAFA"

# 悬停叠加颜色：半透明白色，适用于鼠标悬停时的视觉反馈
HoverOverlayColor = "#33cccccc"

# 按下叠加颜色：稍深的透明白色，适用于鼠标按下时的视觉反馈
PressedOverlayColor = "#55cccccc"

# 强调叠加颜色：稍亮的蓝色，用于高亮显示
AccentOverlayColor = "#44eeeeee"

# 开关开启颜色：绿色，表示开关状态为开启
SwitchOnColor = "#66BB6A"

# 开关关闭颜色：红色，表示开关状态为关闭
SwitchOffColor = "#EF5350"

# 阴影颜色：浅灰色，用于元素的阴影
ShadowColor = "#aaaaaa"

# 弱强调背景色：深灰色，用于次要交互元素的背景
WeakAccentBackgroundColor = "#2C2C2C"

# 弱强调前景色：中灰色，用于次要交互元素的文本
WeakAccentForegroundColor = "#B0B0B0"

# 提醒色：橙色，用于提醒用户的提示
AlertColor = "#FF9800"

# 警示色：黄色，用于警示信息
WarningColor = "#FFC107"

# 警告色：深红色，用于错误或严重问题
DangerColor = "#D32F2F"

# 强调区域标记颜色：深蓝色，用于标记强调区域高亮元素
AccentHighlightColor = "#1976D2"

# 强调区域标记前景色：白色，用于强调区域高亮元素的文本
AccentHighlightForegroundColor = "#FFFFFF"
