BackgroundColor = "White"
ForegroundColor = "MidnightBlue"
AccentBackgroundColor = "DodgerBlue"
AccentForegroundColor = "Azure"
HoverOverlayColor = "#10000000"
PressedOverlayColor = "#15000000"
AccentOverlayColor = "#44eeeeee"
SwitchOnColor = "LightSeaGreen"
SwitchOffColor = "LightCoral"
ShadowColor = "Black"
WeakAccentBackgroundColor = "#f5f6fa"
WeakAccentForegroundColor = "DarkGray"
AlertColor = "Gold"
WarningColor = "Orange"
DangerColor = "Red"
AccentHighlightColor = "#1976D2"
AccentHighlightForegroundColor = "#FFFFFF"
