BackgroundColor = "White"
ForegroundColor = "MidnightBlue"
AccentBackgroundColor = "DodgerBlue"
AccentForegroundColor = "Azure"
HoverOverlayColor = "#10000000"
PressedOverlayColor = "#15000000"
AccentOverlayColor = "DeepSkyBlue"
SwitchOnColor = "LightSeaGreen"
SwitchOffColor = "LightCoral"
ShadowColor = "Black"
WeakAccentBackgroundColor = "LightGray"
WeakAccentForegroundColor = "DarkGray"
AlertColor = "Gold"
WarningColor = "Orange"
DangerColor = "Red"
EmphasisHighlightColor = "White"
