[[Groups]]
Title = "外观"
Key = "Appearance"

[[Groups.Items]]
Name = "主题"
Key = "Theme"
Type = "System.String"
ControlType = "ComboBox"
ControlStyle = "ColorComboBox"
Options = ["lightTheme", "darkTheme"]
IsEnable = true
Tip = "更换主题后部分部件不会立即生效，请重启应用"

[[Groups.Items]]
Name = "语言"
Key = "Language"
Type = "System.String"
ControlType = "ComboBox"
ControlStyle = "DefaultComboBox"
Options = ["简体中文", "English"]
IsEnable = false
Tip = "选择应用的语言"

[[Groups.Items]]
Name = "默认字体"
Key = "Font"
Type = "System.String"
ControlType = "ComboBox"
ControlStyle = "DefaultComboBox"
Options = ["微软雅黑", "宋体", "黑体", "Arial"]
IsEnable = true
Tip = "选择应用的默认字体"
