[[Groups]]
Title = "外观"
Key = "Appearance"

[[Groups.Items]]
Name = "主题"
Key = "Theme"
Type = "String"
ControlType = "ComboBox"
ControlStyle = "ColorComboBox"
Default = "lightTheme"
Values = ["lightTheme", "darkTheme"]
Options = ["浅色主题", "深色主题"]
IsEnable = true
Tip = "选择应用的主题"

[[Groups.Items]]
Name = "语言"
Key = "Language"
Type = "String"
ControlType = "ComboBox"
ControlStyle = "DefaultComboBox"
Default = "zh-CN"
Values = ["zh-CN", "en-US"]
Options = ["简体中文", "English"]
IsEnable = false
Tip = "选择应用的语言"

[[Groups.Items]]
Name = "默认字体"
Key = "Font"
Type = "String"
ControlType = "ComboBox"
ControlStyle = "DefaultComboBox"
Default = "Microsoft YaHei"
Values = ["Microsoft YaHei", "SimSun", "SimHei", "Arial"]
Options = ["微软雅黑", "宋体", "黑体", "Arial"]
IsEnable = true
Tip = "选择应用的默认字体"
